server:
  port: ${SERVER_PORT:8084}

cce:
  cache:
    ttl:
      metrics: 5
      analytics: 10
      lookups: 15

spring:
  datasource:
    url: jdbc:clickhouse://${DB_HOST:cce-clickhouse}:${DB_PORT:8123}/${DB_NAME:cce_analytics}
    username: ${DB_USERNAME:cce_pipeline}
    password: ${DB_PASSWORD:cce_analytics_dev}
